apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      initContainers:
      - name: init-redis
        command: ["bash", "-c", "
              set -ex\n
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1\n
              [[ -f /mnt/conf/redis.conf ]] && exit 0\n
              ordinal=${BASH_REMATCH[1]}\n
              # Copy appropriate conf.d files from config-map to emptyDir.\n
              cp /mnt/config-map/shared.conf /mnt/conf/redis.conf\n
              # ordinal 0 is the first host\n
              if [[ $ordinal -eq 0 ]]; then\n
                cat /mnt/config-map/master.conf >> /mnt/conf/redis.conf\n
              else\n
                cat /mnt/config-map/slave.conf >> /mnt/conf/redis.conf\n
              fi\n
            "]
        image:  image-registry.openshift-image-registry.svc:5000/mpajak/redis
        volumeMounts:
        - name: data
          mountPath: /data
        - name: conf
          mountPath: /mnt/conf
        - name: config-map
          mountPath: /mnt/config-map
      containers:
      - name: redis
        command: ["/opt/rh/rh-redis32/root/usr/bin/redis-server", "/etc/redis/redis.conf"]
        image:  image-registry.openshift-image-registry.svc:5000/mpajak/redis
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
        - name: conf
          mountPath: /etc/redis
        resources:
          requests:
            cpu: 100m
            memory: 4Gi
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "/opt/rh/rh-redis32/root/usr/bin/redis-cli -h $(hostname) ping"
          initialDelaySeconds: 15
          timeoutSeconds: 5
      volumes:
      - name: config-map
        configMap:
          name: redis
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: longhorn
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 500Mi
  - metadata:
      name: conf
      annotations:
        volume.alpha.kubernetes.io/storage-class: longhorn
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Mi

